#!/usr/bin/python3

"""Should factorize the given set of numbers in a file
to produce of two small numbers"""

from sys import argv


def factorize(number_to_check):
    """"Expected to find two small numbers which
    multiply to give a given number"""
    i = 2

    if number_to_check < 2:
        return
    
    while number_to_check % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(number_to_check, number_to_check / i, i))

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            number_to_check = int(line.split('\n')[0])
            factorize(number_to_check)
            line = file.readline()
except:
    pass
